print("@ @ @ @ @ @ @ @   @ @ @ @ @ @ @ @         @   @    @   @         @             @")
print("       @         @                     @                   @     @             @")
print("       @         @                    @                     @    @             @")
print("       @         @                    @                          @             @")
print("       @         @                     @                         @             @")
print("       @         @                       @                       @             @")
print("       @         @ @ @ @ @ @ @ @              @                  @ @ @ @ @ @ @ @")
print("       @         @                                 @             @             @")
print("       @         @                                    @          @             @")
print("       @         @                                      @        @             @")
print("       @         @                                      @        @             @")
print("       @         @                 @                    @        @             @")
print("       @         @                  @                  @         @             @")
print("@ @ @ @           @ @ @ @ @ @ @ @      @   @    @   @            @             @")
print("=================================================================================\n\n")

print("And my logo\n")


print("                 @       @      @ ")
print("           @                          @  ")
print("       @                                  @ ")
print("    @                                        @ ")
print("   @                                           @ ")
print("  @                                             @ ")
print(" @                                              @ ")
print(" @                                               ")
print(" @                      0101010101010101010101010101010101010101")
print(" @                                              ")
print("  @                                            @ ")
print("   @                                           @ ")
print("    @                                         @ ")
print("      @                                     @ ")
print("         @                                @ ")
print("             @                       @ ")
print("                   @    @     @ ")




